print(f'Bienvenido a la calculadora de IMC (Índice de Masa Corporal), por favor, indique su peso y altura.')
altura = float(input('Ingrese aquí su altura en metros: '))
peso = int(input('Ahora ingrese su peso en Kg: '))
resultado = peso / (altura ** 2)
print(f'Usted mide {altura} metros y pesa {peso} Kg, por lo que su IMC marca: {resultado:.2f}')
