nota1 = input('ingrese la primera nota: ')
nota1 = int(nota1)
nota2 = input('ingrese la segunda nota: ')
nota2 = int(nota2)
nota3 = input('ingrese la tercer nota: ')
nota3 = int(nota3)
nota4 = input('ingrese la cuarta nota: ')
nota4 = int(nota4)
resultado = nota1 + nota2 + nota3 + nota4
print(f'El promedio de las notas {nota1}, {nota2}, {nota3} y {nota4} es {resultado / 4}')
